export const steps = [
  {
    title: 'Branding',
    subtitles: [
      'Brand Establishment',
      'Messaging and Strategy',
      'Collateral and Presentation',
    ],
    image: 'branding',
    width: 50,
    height: 146,
    className: 'top-[440px] left-[-60px]',
    deg: -6,
  },
  {
    title: 'Data Analysis',
    subtitles: [
      'Data Infrastructure',
      'Advanced Analytics',
      'Marketing Insights',
    ],
    image: 'data-analysis',
    width: 166,
    height: 202,
    className: 'top-[70px] left-[-30px]',
    deg: 35,
  },
  {
    title: 'UI & UX',
    subtitles: ['Strategic Planning', 'User-Centric Design', 'Design Framework'],
    image: 'ui-ux',
    width: 96,
    height: 34,
    className: 'top-[-50px] left-[410px]',
    deg: 89,
  },
  {
    title: 'Development',
    subtitles: ['Web Development', 'Infrastructure', 'Customer Support'],
    image: 'development',
    width: 155,
    height: 178,
    className: 'top-[60px] left-[790px]',
    deg: 142,
  },
  {
    title: 'Digital Marketing',
    subtitles: [
      'Online Visibility',
      'Direct Communication',
      'Strategic Promotion',
    ],
    image: 'digital-marketing',
    width: 56,
    height: 239,
    className: 'top-[360px] left-[940px]',
    deg: 182,
  },
]
