export const users = [
  {
    description: `"Ograviti's commitment and innovation transformed our business. As Tech Innovate Corp's CEO, they're strategic collaborators driving real change."`,
    rate: 5,
    img: '/images/users/1.jpg',
    name: 'Sarah Thompson',
    role: 'CEO of Tech Innovate Corp',
  },
  {
    description: `"Ograviti surpassed expectations, turning ideas into reality. As a small business owner, I appreciate their visionary approach, not just as developers."`,
    rate: 5,
    img: '/images/users/2.jpg',
    name: 'Jason Rodriguez',
    role: 'Small Business Owner',
  },
  {
    description: `"Ograviti's rare blend of tech expertise delivers transformative results across industries with strategic brilliance consistently."`,
    rate: 5,
    img: '/images/users/3.jpg',
    name: ' Dr. Emily Chang',
    role: ' Tech Analyst and Consultant',
  },
  {
    description: `"Ograviti, a game-changer. As CTO at InnovateTech Solutions, I've seen their dedication exceed expectations, making them reliable for cutting-edge initiatives."`,
    rate: 5,
    img: '/images/users/4.jpg',
    name: 'Alex Patel',
    role: 'InnovateTech Solutions',
  },
  {
    description: `"Ograviti's commitment and innovation transformed our business. As Tech Innovate Corp's CEO, they're strategic collaborators driving real change."`,
    rate: 5,
    img: '/images/users/1.jpg',
    name: 'Sarah Thompson',
    role: 'CEO of Tech Innovate Corp',
  },
  {
    description: `"Ograviti surpassed expectations, turning ideas into reality. As a small business owner, I appreciate their visionary approach, not just as developers."`,
    rate: 5,
    img: '/images/users/2.jpg',
    name: 'Jason Rodriguez',
    role: 'Small Business Owner',
  },
  {
    description: `"Ograviti's rare blend of tech expertise delivers transformative results across industries with strategic brilliance consistently."`,
    rate: 5,
    img: '/images/users/3.jpg',
    name: ' Dr. Emily Chang',
    role: ' Tech Analyst and Consultant',
  },
  {
    description: `"Ograviti, a game-changer. As CTO at InnovateTech Solutions, I've seen their dedication exceed expectations, making them reliable for cutting-edge initiatives."`,
    rate: 5,
    img: '/images/users/4.jpg',
    name: 'Alex Patel',
    role: 'InnovateTech Solutions',
  },
]
